"""Add date_added to conference

Revision ID: 7a670c3cb5a0
Revises: 9d27f6b5ce5e
Create Date: 2024-10-21 18:07:39.069638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a670c3cb5a0'
down_revision = '9d27f6b5ce5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
