"""Add foreign key relationship between Conference and ConferenceDetail

Revision ID: eb3460651902
Revises: cc663417e557
Create Date: 2024-10-27 21:34:22.075799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3460651902'
down_revision = 'cc663417e557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x')
    op.drop_table('task')
    with op.batch_alter_table('conferenceDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conference_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'conference', ['conference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferenceDetails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conference_id')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('conference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_table('x',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('a', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('b', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='x_pkey')
    )
    # ### end Alembic commands ###
